---
# main variables
mkaction: 'unknown'   # can be deploy,destroy

# volume pool default variables
vol_pool:
  name: 'virt-volumes'
  path: '/tmp/virt-volumes'
  create: 'yes'

# network default variables
virt_networks:
  os_external:
    network_cidr: '192.168.100.0/24'
    mode: 'nat'                       # can be 'isolated', 'nat'
    create: 'yes'
  os_internal:
    network_cidr: '192.168.110.0/24'
    mode: 'isolated'                       # can be 'isolated', 'nat'
    create: 'yes'
  os_storage:
    network_cidr: '192.168.120.0/24'
    mode: 'isolated'                       # can be 'isolated', 'nat'
    create: 'yes'
  os_tunnel:
    network_cidr: '192.168.130.0/24'
    mode: 'isolated'                       # can be 'isolated', 'nat'
    create: 'yes'
  os_provider:
    network_cidr: '192.168.140.0/24'
    mode: 'isolated'                       # can be 'isolated', 'nat'
    create: 'yes'

    # routing_rools:
    #  internal_to_storage:
    #    net1: 'os_internal'
    #    net2: 'os_storage'
    #  internal_to_provider:
    #    net1: 'os_internal'
    #    net2: 'os_provider'

# virtual machines default variables
domain_name: "kemopq1.test"
ssh_my_pub_key: "/home/kpog/.ssh/id_rsa.pub"

virt_machines:
  faikolla:
    name: 'fai-kolla-srv'
    nr_of_nodes: 1
    memory: 2048
    vcpu: 1
    boot_mode: 'image'    # can be image, PXE or UEFI
    start: 'immediately'
    volumes:
      boot:
        size: '50G'
        image: '/home/kpog/WORK/downloads/ubuntu-18.04-server-cloudimg-1.0.0-amd64.qcow2'
    net_interfaces:
      public:
        ext_bridge: 'br-main'
        address_cidr: '172.30.21.43/22'
        gateway: '172.30.20.1'
        nameservers:
          - '10.1.2.3'
      internal:
        network: 'os_internal'
        address_cidr: '192.168.110.5/24'
        include_to_hosts: 'yes'

  osnodes:
    name: vmcloud
    nr_of_nodes: 1
    memory: 16384
    vcpu: 2
    boot_mode: 'uefi'
    start: 'later'
    volumes:
      boot:
        size: '200G'
      ceph:
        size: '50G'
    net_interfaces:
      external:
        network: 'os_external'
      internal:
        network: 'os_internal'
        address_cidr: '192.168.110.11/24'    # only needed when include_to_hosts is yes
        include_to_hosts: 'yes'
        boot: 'yes'
      storage:
        network: 'os_storage'
      provider:
        network: 'os_provider'
