---
############################################################
#  tasks file for crating virt-resources
############################################################

- name: Include tasks vol_pool_deploy.yml
  include_tasks: 'vol_pool_deploy.yml'
  when: (virt_resources_type is defined) and ((virt_resources_type == 'all') or (virt_resources_type == 'virt_vol_pool')) and
        (vol_pool is defined) and vol_pool

- name: Include tasks network_deploy.yml
  include_tasks: 'network_deploy.yml'
  when: (virt_resources_type is defined) and ((virt_resources_type == 'all') or (virt_resources_type == 'virt_network')) and
        (virt_networks is defined) and virt_networks

- name: Include tasks vm_deploy.yml
  include_tasks: 'vm_deploy.yml'
  when: (virt_resources_type is defined) and ((virt_resources_type == 'all') or (virt_resources_type == 'virt_machine')) and
        (virt_machines is defined) and virt_machines
