---
############################################################
#  tasks file for crating virt-resources
############################################################

- name: Install python lxml package
  pip:
    name:
      - lxml

- name: Include tasks vol_pool_deploy.yml
  include_tasks: 'vol_pool_deploy.yml'
  when: vol_pool is defined and vol_pool

- name: Include tasks network_deploy.yml
  include_tasks: 'network_deploy.yml'
  when: virt_networks is defined and virt_networks

- name: Include tasks vm_deploy.yml
  include_tasks: 'vm_deploy.yml'
  when: virt_machines is defined and virt_machines
