---
############################################################
#  tasks file for destroying virt-resources
############################################################
- name: Include tasks vm_destroy
  include_tasks: 'vm_destroy.yml'
  when: (virt_resources_type is defined) and ((virt_resources_type == 'all') or (virt_resources_type == 'virt_machine')) and
        (virt_machines is defined) and virt_machines

- name: Include tasks network_destroy
  include_tasks: 'network_destroy.yml'
  when: (virt_resources_type is defined) and ((virt_resources_type == 'all') or (virt_resources_type == 'virt_network')) and
        (virt_networks is defined) and virt_networks

- name: Include tasks vol_pool_destroy
  include_tasks: 'vol_pool_destroy.yml'
  when: (virt_resources_type is defined) and ((virt_resources_type == 'all') or (virt_resources_type == 'virt_vol_pool')) and
        (vol_pool is defined) and vol_pool
