---
############################################################
#  tasks file for destroying virt-resources
############################################################
- name: Include tasks vm_destroy
  include_tasks: 'vm_destroy.yml'
  when: virt_machines is defined and virt_machines

- name: Include tasks network_destroy
  include_tasks: 'network_destroy.yml'
  when: virt_networks is defined and virt_networks

- name: Include tasks vol_pool_destroy
  include_tasks: 'vol_pool_destroy.yml'
  when: vol_pool is defined and vol_pool
