---
############################################################
#  tasks file for destroying virtual networks
############################################################
- name: Import network_check.yml
  import_tasks: 'network_check.yml'

- name: Disable routing block
  block:

    - name: Disable routing between two virtual networks
      vars:
        net1_name: "{{ item.value.net1 }}"
        net2_name: "{{ item.value.net2 }}"
      shell: |
        iptables -I FORWARD -i "br-{{ net1_name[:10] }}" -o "br-{{ net2_name[:10] }}" -j ACCEPT
        iptables -I FORWARD -i "br-{{ net2_name[:10] }}" -o "br-{{ net1_name[:10] }}" -j ACCEPT
      become: true
      when: (net1_name in netlist.list_nets) and
            (net2_name in netlist.list_nets)
      loop: "{{ routing_rools | dict2items }}"

  when: routing_rools is defined

- name: Stop virtual network
  virt_net:
    command: destroy
    name: "{{ item.key }}"
  when: item.key in netlist.list_nets
  ignore_errors: 'yes'
  loop: "{{ virt_networks | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Remove virtual network
  virt_net:
    command: undefine
    name: "{{ item.key }}"
  when: item.key in netlist.list_nets
  ignore_errors: 'yes'
  loop: "{{ virt_networks | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
