---
############################################################
#  tasks file for crating virtual networks
############################################################
- name: Check some variables and print interesting information
  import_tasks: 'network_check.yml'

- name: Network loop for each network
  include_tasks: 'network_loop_deploy.yml'
  loop: "{{ virt_networks | dict2items }}"
  loop_control:
    loop_var: ii_network
    label: "{{ ii_network.key }}"
  when: (ii_network.value.create is defined) and (ii_network.value.create | bool) and
        ((ii_network.value.virtualization_host is not defined) or (ii_network.value.virtualization_host == inventory_hostname)) and
        (ii_network.key not in netlist.list_nets)

- name: Read virtual networks after creation
  virt_net:
    command: list_nets
    name: unknown
  register: netlist

- name: Print active virtual networks after creation
  debug:
    var: netlist.list_nets

- name: Enable routing block
  block:

    - name: Enabling routing between two virtual networks
      vars:
        net1_name: "{{ item.value.net1 }}"
        net2_name: "{{ item.value.net2 }}"
      shell: |
        iptables -I FORWARD 1 -i "br-{{ net1_name[:10] }}" -o "br-{{ net2_name[:10] }}" -j ACCEPT
        iptables -I FORWARD 1 -i "br-{{ net2_name[:10] }}" -o "br-{{ net1_name[:10] }}" -j ACCEPT
      become: true
      when: (net1_name in netlist.list_nets) and
            (net2_name in netlist.list_nets)
      loop: "{{ routing_rools | dict2items }}"

  when: routing_rools is defined
