---
############################################################
#  tasks file for crating virt-resources
############################################################
- name: List virtual networks
  virt_net:
    command: list_nets
    name: unknown
  register: netlist

- name: Create repo net
  vars:
    net_name: "{{ net_repo_ext.name }}"
    net_cidr: "{{ net_repo_ext.network_cidr }}"
  virt_net:
    command: define
    name: "{{ net_repo_ext.name }}"
    xml: "{{ lookup('template', 'net-os-other.xml.j2') }}"
  when: (vm_repo is defined) and
        (net_repo_ext.name not in netlist.list_nets)

- name: Repo net will be started at boot
  virt_net:
    autostart: 'yes'
    name: "{{ net_repo_ext.name }}"
  when: (vm_repo is defined) and
        (net_repo_ext.name not in netlist.list_nets)

- name: Run repo net
  virt_net:
    command: create
    name: "{{ net_repo_ext.name }}"
  when: (vm_repo is defined) and
        (net_repo_ext.name not in netlist.list_nets)

- name: Create faikolla net
  vars:
    net_name: "{{ net_faikolla_ext.name }}"
    net_cidr: "{{ net_faikolla_ext.network_cidr }}"
  virt_net:
    command: define
    name: "{{ net_faikolla_ext.name }}"
    xml: "{{ lookup('template', 'net-os-other.xml.j2') }}"
  when: (vm_repo is defined) and
        (net_faikolla_ext.name not in netlist.list_nets)

- name: Faikolla net will be started at boot
  virt_net:
    autostart: 'yes'
    name: "{{ net_faikolla_ext.name }}"
  when: (vm_repo is defined) and
        (net_faikolla_ext.name not in netlist.list_nets)

- name: Run faikolla net
  virt_net:
    command: create
    name: "{{ net_faikolla_ext.name }}"
  when: (vm_repo is defined) and
        (net_faikolla_ext.name not in netlist.list_nets)

- name: Create external net
  vars:
    net_name: "{{ net_external.name }}"
    net_cidr: "{{ net_external.network_cidr }}"
    include_nat_section: "{% if vm_repo is defined %}no{% else %}yes{% endif %}"
  virt_net:
    command: define
    name: "{{ net_external.name }}"
    xml: "{{ lookup('template', 'net-os-other.xml.j2') }}"
  when: (net_external.name not in netlist.list_nets)

- name: External net will be started at boot
  virt_net:
    autostart: 'yes'
    name: "{{ net_external.name }}"
  when: (net_external.name not in netlist.list_nets)

- name: Run external net
  virt_net:
    command: create
    name: "{{ net_external.name }}"
  when: (net_external.name not in netlist.list_nets)

- name: Create internal net
  vars:
    net_name: "{{ net_internal.name }}"
    net_cidr: "{{ net_internal.network_cidr }}"
  virt_net:
    command: define
    name: "{{ net_internal.name }}"
    xml: "{{ lookup('template', 'net-os-other.xml.j2') }}"
  when: (net_internal.name not in netlist.list_nets)

- name: Internal net will be started at boot
  virt_net:
    autostart: 'yes'
    name: "{{ net_internal.name }}"
  when: (net_internal.name not in netlist.list_nets)

- name: Run internal net
  virt_net:
    command: create
    name: "{{ net_internal.name }}"
  when: (net_internal.name not in netlist.list_nets)

- name: Create storage net
  vars:
    net_name: "{{ net_storage.name }}"
    net_cidr: "{{ net_storage.network_cidr }}"
  virt_net:
    command: define
    name: "{{ net_storage.name }}"
    xml: "{{ lookup('template', 'net-os-other.xml.j2') }}"
  when: (net_storage.name not in netlist.list_nets)

- name: Storage net will be started at boot
  virt_net:
    autostart: 'yes'
    name: "{{ net_storage.name }}"
  when: (net_storage.name not in netlist.list_nets)

- name: Run storage net
  virt_net:
    command: create
    name: "{{ net_storage.name }}"
  when: (net_storage.name not in netlist.list_nets)

- name: Create tunnel net
  vars:
    net_name: "{{ net_tunnel.name }}"
    net_cidr: "{{ net_tunnel.network_cidr }}"
  virt_net:
    command: define
    name: "{{ net_tunnel.name }}"
    xml: "{{ lookup('template', 'net-os-other.xml.j2') }}"
  when: (net_tunnel.name not in netlist.list_nets)

- name: Tunnel net will be started at boot
  virt_net:
    autostart: 'yes'
    name: "{{ net_tunnel.name }}"
  when: (net_tunnel.name not in netlist.list_nets)

- name: Run tunnel net
  virt_net:
    command: create
    name: "{{ net_tunnel.name }}"
  when: (net_tunnel.name not in netlist.list_nets)

- name: Create provider net
  vars:
    net_name: "{{ net_provider.name }}"
    net_cidr: "{{ net_provider.network_cidr }}"
  virt_net:
    command: define
    name: "{{ net_provider.name }}"
    xml: "{{ lookup('template', 'net-os-other.xml.j2') }}"
  when: (net_provider.name not in netlist.list_nets)

- name: Provider net will be started at boot
  virt_net:
    autostart: 'yes'
    name: "{{ net_provider.name }}"
  when: (net_provider.name not in netlist.list_nets)

- name: Run provider net
  virt_net:
    command: create
    name: "{{ net_provider.name }}"
  when: (net_provider.name not in netlist.list_nets)

- name: Connect fai-kolla net and external net
  shell: |
    iptables -I FORWARD 1 -i "br-{{ net_faikolla_ext.name[:10] }}" -o "br-{{ net_external.name[:10] }}" -j ACCEPT
    iptables -I FORWARD 1 -i "br-{{ net_external.name[:10] }}" -o "br-{{ net_faikolla_ext.name[:10] }}" -j ACCEPT
  become: true
  when: (vm_repo is defined) and
        (net_faikolla_ext.name not in netlist.list_nets)

- name: Connect repo net and fai-kolla net
  shell: |
    iptables -I FORWARD 1 -i "br-{{ net_repo_ext.name[:10] }}" -o "br-{{ net_faikolla_ext.name[:10] }}" -j ACCEPT
    iptables -I FORWARD 1 -i "br-{{ net_faikolla_ext.name[:10] }}" -o "br-{{ net_repo_ext.name[:10] }}" -j ACCEPT
  become: true
  when: (vm_repo is defined) and
        (net_repo_ext.name not in netlist.list_nets)

- name: Connect repo net and external net
  shell: |
    iptables -I FORWARD 1 -i "br-{{ net_repo_ext.name[:10] }}" -o "br-{{ net_external.name[:10] }}" -j ACCEPT
    iptables -I FORWARD 1 -i "br-{{ net_external.name[:10] }}" -o "br-{{ net_repo_ext.name[:10] }}" -j ACCEPT
  become: true
  when: (vm_repo is defined) and
        (net_repo_ext.name not in netlist.list_nets)
