---
############################################################
#  tasks file for printing interesting information 
############################################################
- name: List vms
  virt:
    command: list_vms
  register: vm_list

- name: Print running vms
  debug:
    var: vm_list

- name: List volumes on virtual pool
  command: "virsh vol-list {{ vol_pool.name }}"
  register: vol_list

- name: Print available volumes
  debug:
    var: vol_list

- name: List all qcow images in "{{ vol_pool.path }}" folder
  find:
    paths: "{{ vol_pool.path }}"
    file_type: file
    use_regex: 'yes'
    patterns: '*.qcow2'
  register: image_list

- name: Print existing images
  debug:
    var: image_list
