---
##################################################################
# tasks file for destroying virtual machines
##################################################################
- name: Print interesting information
  import_tasks: vm_check.yml

- name: VM loop for each vm type
  include_tasks: vm_loop_destroy.yml
  loop: "{{ virt_machines | dict2items }}"
  loop_control:
    loop_var: ii_vm
    label: "{{ ii_vm.key }}"
  when: ((virt_machines_type is not defined) or (ii_vm.key in virt_machines_type)) and
        (ii_vm.value.create | bool)
