---
############################################################
# tasks file for running instance of vm type
############################################################
- name: Set vm_name variable
  vars:
    vm_name_pre: "{{ (ii_vm.value.name is defined) | ternary(ii_vm.value.name, ii_vm.key) }}"
  set_fact:
    vm_name: "{{ vm_name_pre }}{{ hostname_suffix }}{{ ii_index }}"

- name: Check status of VM "{{ vm_name }}"
  virt:
    name: "{{ vm_name }}"
    command: status
  register: vm_status

- name: Set fact status of VM
  set_fact:
    vm_status_fact: "{{ vm_status.status }}"
  when: (vm_status.status is defined) and (ii_index == 1)

- name: Run vm
  virt:
    name: "{{ vm_name }}"
    command: start
  when: (vm_status.status is defined) and
        (vm_status.status == 'shutdown')
