---
############################################################
# tasks file for making additional actions on running vm
############################################################
- name: Set vm_name variable
  vars:
    vm_name_pre: "{{ (ii_vm.value.name is defined) | ternary(ii_vm.value.name, ii_vm.key) }}"
  set_fact:
    vm_name: "{{ vm_name_pre }}{{ hostname_suffix }}{{ ii_index }}"

- name: Get OS version
  block:

    - name: Check OS version of image
      kemopq.virtual_resources.get_os_version:
        vm_name: "{{ vm_name }}"
      register: get_os_version_result

    - name: Set fact OS version
      set_fact:
        os_version: "{{ get_os_version_result.os_version }}"

    - name: Print OS version of image
      debug:
        msg: "OS version of vm {{ vm_name }} is  {{ os_version }}"

  when: ii_vm.value.boot_mode == 'image'

- name: Resize volume block
  vars:
    vm_hostname: "{{ (domain_name is defined) | ternary(vm_name + '.' + domain_name, vm_name) }}"
  delegate_to: "{{ vm_hostname }}"
  remote_user: root
  block:

    - name: Wait for server to become active
      wait_for_connection:
        delay: 1
        timeout: 100

    - name: Resize volume (ubuntu, debian)
      shell: "growpart /dev/vda 1; resize2fs /dev/vda1"
      when: (os_version.distro == 'debian') or (os_version.distro == 'ubuntu')

    - name: Resize volume (centos)
      shell: "growpart /dev/vda 1; xfs_growfs /dev/vda1"
      when: (os_version.distro == 'centos')

    - name: Activate PasswordAuthentication
      vars:
        pass_auth_option: "{% if (ii_vm.value.ssh_password_auth is defined) and (ii_vm.value.ssh_password_auth == 'yes') %}yes{% else %}no{% endif %}"
      lineinfile:
        path: "/etc/ssh/sshd_config"
        line: "PasswordAuthentication {{ pass_auth_option }}"
        state: present

    - name: Ensure PasswordAuthentication is activated
      vars:
        pass_auth_reverse_option: "{% if (ii_vm.value.ssh_password_auth is defined) and (ii_vm.value.ssh_password_auth == 'yes') %}no{% else %}yes{% endif %}"
      lineinfile:
        path: "/etc/ssh/sshd_config"
        line: "PasswordAuthentication {{ pass_auth_reverse_option }}"
        state: absent

    - name: Restart service sshd
      service:
        name: sshd
        state: restarted

  when: (ii_vm.value.boot_mode == 'image') and
        (vm_status_fact is defined) and
        (vm_status_fact == 'shutdown')
