---
###############################################################
# tasks file for creating all instances of virtual machine type
###############################################################
- name: Check if number of instances > 0
  assert:
    that:
      - ii_vm.value.nr_of_nodes is defined
      - ii_vm.value.nr_of_nodes > 0
    fail_msg: "VM({{ ii_vm.key }}) nr_of_nodes not defined or has incorrect value"
    quiet: 'yes'

- name: Check if instances data are available for all instances
  assert:
    that:
      - (ii_vm.value.instances is not defined) or (ii_vm.value.instances | length == ii_vm.value.nr_of_nodes)
    fail_msg: "for VM({{ ii_vm.key }}) instances list size is not the same as nr_of_nodes"
    quiet: 'yes'

- name: Loop of all instances of vm
  include_tasks: vm_inst_loop_deploy.yml
  loop: "{{ range(1, ii_vm.value.nr_of_nodes + 1) | list }}"
  loop_control:
    loop_var: ii_index
  when: (((ii_vm.value.virtualization_host is not defined) and
          (ii_vm.value.instances[ii_index - 1].virtualization_host is not defined)) or
         ((ii_vm.value.instances[ii_index - 1].virtualization_host is defined) and
          (ii_vm.value.instances[ii_index - 1].virtualization_host == inventory_hostname)) or
         ((ii_vm.value.instances[ii_index - 1].virtualization_host is not defined) and
          (ii_vm.value.virtualization_host is defined) and
          (ii_vm.value.virtualization_host == inventory_hostname)))

- name: Loop of all instances of vm for starting vm
  include_tasks: vm_inst_loop_vmstart.yml
  loop: "{{ range(1, ii_vm.value.nr_of_nodes + 1) | list }}"
  loop_control:
    loop_var: ii_index
  when: (((ii_vm.value.virtualization_host is not defined) and
          (ii_vm.value.instances[ii_index - 1].virtualization_host is not defined)) or
         ((ii_vm.value.instances[ii_index - 1].virtualization_host is defined) and
          (ii_vm.value.instances[ii_index - 1].virtualization_host == inventory_hostname)) or
         ((ii_vm.value.instances[ii_index - 1].virtualization_host is not defined) and
          (ii_vm.value.virtualization_host is defined) and
          (ii_vm.value.virtualization_host == inventory_hostname))) and
        (ii_vm.value.start == 'immediately')

- name: Loop of all instances of vm for making additional actions
  include_tasks: vm_inst_loop_addact.yml
  loop: "{{ range(1, ii_vm.value.nr_of_nodes + 1) | list }}"
  loop_control:
    loop_var: ii_index
  when: (((ii_vm.value.virtualization_host is not defined) and
          (ii_vm.value.instances[ii_index - 1].virtualization_host is not defined)) or
         ((ii_vm.value.instances[ii_index - 1].virtualization_host is defined) and
          (ii_vm.value.instances[ii_index - 1].virtualization_host == inventory_hostname)) or
         ((ii_vm.value.instances[ii_index - 1].virtualization_host is not defined) and
          (ii_vm.value.virtualization_host is defined) and
          (ii_vm.value.virtualization_host == inventory_hostname))) and
        (ii_vm.value.start == 'immediately')
