---
###############################################################
# tasks file for running all instances of virtual machine type
###############################################################
- name: Loop of all instances of vm for starting vm
  include_tasks: vm_inst_loop_vmstart.yml
  loop: "{{ range(1, ii_vm.value.nr_of_nodes + 1) | list }}"
  loop_control:
    loop_var: ii_index
  when: ((ii_vm.value.virtualization_host is not defined) or
        (((ii_vm.value.virtualization_host | type_debug) == 'str') and (ii_vm.value.virtualization_host == inventory_hostname)) or
        (ii_vm.value.virtualization_host[ii_index - 1] == inventory_hostname)) and
        (ii_vm.value.start == 'later')

- name: Loop of all instances of vm for making additional actions
  include_tasks: vm_inst_loop_addact.yml
  loop: "{{ range(1, ii_vm.value.nr_of_nodes + 1) | list }}"
  loop_control:
    loop_var: ii_index
  when: ((ii_vm.value.virtualization_host is not defined) or
        (((ii_vm.value.virtualization_host | type_debug) == 'str') and (ii_vm.value.virtualization_host == inventory_hostname)) or
        (ii_vm.value.virtualization_host[ii_index - 1] == inventory_hostname)) and
        (ii_vm.value.start == 'later')
