---
#################################################################
# tasks file for destroying all instances of virtual machine type
#################################################################
- name: Check if number of instances > 0
  assert:
    that:
      - ii_vm.value.nr_of_nodes is defined
      - ii_vm.value.nr_of_nodes > 0
    fail_msg: "VM nr_of_nodes not defined or has incorrect value"
    quiet: 'yes'

- name: Loop of all instances of vm
  include_tasks: vm_inst_loop_destroy.yml
  loop: "{{ range(1, ii_vm.value.nr_of_nodes + 1) | list }}"
  loop_control:
    loop_var: ii_index
  when: (((ii_vm.value.virtualization_host is not defined) and
          (ii_vm.value.instances[ii_index - 1].virtualization_host is not defined)) or
         ((ii_vm.value.instances[ii_index - 1].virtualization_host is defined) and
          (ii_vm.value.instances[ii_index - 1].virtualization_host == inventory_hostname)) or
         ((ii_vm.value.instances[ii_index - 1].virtualization_host is not defined) and
          (ii_vm.value.virtualization_host is defined) and
          (ii_vm.value.virtualization_host == inventory_hostname)))
