---
###############################################################
# tasks file for creating all instances of virtual machine type
###############################################################
- name: Check if vms has at least one network
  assert:
    that:
      - ii_vm.value.net_interfaces is defined
      - ii_vm.value.net_interfaces
    fail_msg: "VM has not properly defined networks"
    quiet: 'yes'

- name: Check if vms has boot volume
  vars:
    vol_key: "boot"
  assert:
    that:
      - ii_vm.value.volumes is defined
      - ii_vm.value.volumes
      - vol_key in ii_vm.value.volumes
    fail_msg: "VM has not properly defined volumes"
    quiet: 'yes'

- name: Check if number of instances > 0
  assert:
    that:
      - ii_vm.value.nr_of_nodes is defined
      - ii_vm.value.nr_of_nodes > 0
    fail_msg: "VM nr_of_nodes not defined or has incorrect value"
    quiet: 'yes'

- name: Loop of all instances of vm
  include_tasks: vm_inst_loop_deploy.yml
  loop: "{{ range(1, ii_vm.value.nr_of_nodes + 1) | list }}"
  loop_control:
    loop_var: ii_index
  when: (ii_vm.value.virtualization_host is not defined) or
        (((ii_vm.value.virtualization_host | type_debug) == 'str') and (ii_vm.value.virtualization_host == inventory_hostname)) or
        (ii_vm.value.virtualization_host[ii_index - 1] == inventory_hostname)

- name: Loop of all instances of vm for starting vm
  include_tasks: vm_inst_loop_vmstart.yml
  loop: "{{ range(1, ii_vm.value.nr_of_nodes + 1) | list }}"
  loop_control:
    loop_var: ii_index
  when: ((ii_vm.value.virtualization_host is not defined) or
        (((ii_vm.value.virtualization_host | type_debug) == 'str') and (ii_vm.value.virtualization_host == inventory_hostname)) or
        (ii_vm.value.virtualization_host[ii_index - 1] == inventory_hostname)) and
        (ii_vm.value.start == 'immediately')

- name: Loop of all instances of vm for making additional actions
  include_tasks: vm_inst_loop_addact.yml
  loop: "{{ range(1, ii_vm.value.nr_of_nodes + 1) | list }}"
  loop_control:
    loop_var: ii_index
  when: ((ii_vm.value.virtualization_host is not defined) or
        (((ii_vm.value.virtualization_host | type_debug) == 'str') and (ii_vm.value.virtualization_host == inventory_hostname)) or
        (ii_vm.value.virtualization_host[ii_index - 1] == inventory_hostname)) and
        (ii_vm.value.start == 'immediately')
