---
############################################################
# tasks file for destroying volumes of vms
############################################################
- name: Set vol_name variable
  vars:
    vol_name_pre: "{{ (ii_vm.value.name is defined) | ternary(ii_vm.value.name, ii_vm.key) }}"
  set_fact:
    vol_name: "{{ vol_name_pre }}-{{ ii_vol.key }}{{ hostname_suffix }}{{ ii_index }}"

- name: Remove volume from pool
  command: "virsh vol-delete --pool {{ vol_pool.name }} {{ vol_name }}.qcow2"
  become: true
  ignore_errors: 'yes'

- name: Check if image file exists on target folder
  stat:
    path: "{{ vol_pool.path }}/{{ vol_name }}.qcow2"
  register: imageonplace

- name: Remove image from target folder
  file:
    path: "{{ vol_pool.path }}/{{ vol_name }}.qcow2"
    state: absent
  when: imageonplace.stat.exists
  ignore_errors: 'yes'
