---
############################################################
# tasks file for creating volumes for vm
############################################################
- name: Set vol_name variable
  set_fact:
    vol_name: "{{ ii_vm.key }}-{{ ii_vol.key }}-node{{ ii_index }}"

- name: Check if image already exists on target folder
  stat:
    path: "{{ vol_pool.path }}/{{ vol_name }}.qcow2"
  register: imageonplace

# boot volume from image
- name: Image boot volume block
  block:

    - name: Copy image to os-volume pool
      command: cp "{{ ii_vol.value.image }}" "{{ vol_pool.path }}/{{ vol_name }}.qcow2"
      when: (not imageonplace.stat.exists)

    - name: Set root password, disable cloud init, inject public ssh key, enable ssh server, set hostname
      command: virt-customize -q -a "{{ vol_pool.path }}/{{ vol_name }}.qcow2"
                              --uninstall cloud-init
                              --ssh-inject "root:file:{{ ssh_my_pub_key }}"
                              --root-password "password:{{ vm_passwd }}"
                              --append-line '/etc/ssh/sshd_config:PermitRootLogin yes'
                              --run-command "dpkg-reconfigure openssh-server"
                              --run-command "systemctl enable ssh.service"
                              --hostname "{{ vm_name }}"
      become: true

    - name: Resize volume
      command: 'qemu-img resize {{ vol_pool.path }}/{{ vol_name }}.qcow2 {{ ii_vol.value.size }}'
      become: true

    - name: Create netplan file
      become: true
      vars:
        interfaces: "{{ ii_vm.value.net_interfaces | kemopq.virtual_resources.netint_to_list }}"
        index: "{{ ii_index - 1 }}"
      template:
        src: 'vm-netplan.j2'
        dest: '/tmp/50-cloud-init.yaml'
        owner: root
        group: root
        mode: 0644

    - name: Copy netplan file to '{{ ii_vm.key }}' server
      become: true
      command: 'virt-copy-in -a {{ vol_pool.path }}/{{ vol_name }}.qcow2 /tmp/50-cloud-init.yaml /etc/netplan'

    - name: Remove tmp file
      become: true
      file:
        path: '/tmp/50-cloud-init.yaml'
        state: absent

  when: (ii_vol.key == 'boot') and (ii_vm.value.boot_mode == 'image') and
        (not imageonplace.stat.exists)

# Create empty volume
- name: Create empty volume
  command: virsh vol-create-as --pool "{{ vol_pool.name }}" --name "{{ vol_name }}.qcow2"
                               --capacity "{{ ii_vol.value.size }}" --format qcow2
  become: true
  when: ((ii_vol.key != 'boot') or (ii_vm.value.boot_mode != 'image')) and
         (not imageonplace.stat.exists)
