---
############################################################
#  tasks file for destroying virtual storage pool
############################################################
- name: Import vol_pool_check.yml
  import_tasks: 'vol_pool_check.yml'

- name: Remove virt-pool block
  block:

    - name: Stop virt-volumes pool
      virt_pool:
        command: destroy
        name: "{{ vol_pool.name }}"
      ignore_errors: 'yes'

    - name: Remove virt-volumes pool
      virt_pool:
        command: undefine
        name: "{{ vol_pool.name }}"
      ignore_errors: 'yes'

  when: (vol_pool.create is defined) and (vol_pool.create | bool) and
        ((vol_pool.virtualization_host is not defined) or (vol_pool.virtualization_host == inventory_hostname)) and
        (vol_pool.name in poollist.list_pools)

- name: Remove virt-volumes folder
  file:
    path: "{{ vol_pool.path }}"
    state: absent
  when: (vol_pool.create is defined) and (vol_pool.create | bool) and
        ((vol_pool.virtualization_host is not defined) or (vol_pool.virtualization_host == inventory_hostname)) and
        folderonplace.stat.exists
  ignore_errors: 'yes'
