---
############################################################
#  tasks file for crating virtual storage pool
############################################################
- name: Import vol_pool_check.yml
  import_tasks: 'vol_pool_check.yml'

- name: Creating virt-volumes folder block
  block:

    - name: Create virt-volumes folder
      file:
        path: "{{ vol_pool.path }}"
        state: directory
        mode: 0755
        recurse: 'yes'

    - name: Pause 2s
      pause:
        seconds: 2

  when: (vol_pool.create is defined) and (vol_pool.create | bool) and
        ((vol_pool.virtualization_host is not defined) or (vol_pool.virtualization_host == inventory_hostname)) and
        (not folderonplace.stat.exists)

- name: Creating vol-pool block
  block:

    - name: Create virt-volumes pool
      virt_pool:
        command: define
        name: "{{ vol_pool.name }}"
        xml: "{{ lookup('template', 'pool-virt-volumes.xml.j2') }}"

    - name: Starts virt-volumes pool
      virt_pool:
        command: create
        name: "{{ vol_pool.name }}"

    - name: Ensure that a pool will be started at boot
      virt_pool:
        autostart: 'yes'
        name: "{{ vol_pool.name }}"

  when: (vol_pool.create is defined) and (vol_pool.create | bool) and
        ((vol_pool.virtualization_host is not defined) or (vol_pool.virtualization_host == inventory_hostname)) and
        (vol_pool.name not in poollist.list_pools)
