---
############################################################
#  tasks file for crating virtual storages
############################################################
- name: Check if folder already exists
  stat:
    path: "{{ vol_pool.path }}"
  register: folderonplace

- name: Create os-volumes folder
  file:
    path: "{{ vol_pool.path }}"
    state: directory
    mode: 0755
    recurse: 'yes'
  when: (not folderonplace.stat.exists)

- name: Pause 2s
  pause:
    seconds: 2
  when: (not folderonplace.stat.exists)

- name: List virtual storage pools
  virt_pool:
    command: list_pools
  register: poollist

- name: Create os-volumes pool
  virt_pool:
    command: define
    name: "{{ vol_pool.name }}"
    xml: "{{ lookup('template', 'pool-os-volumes.xml.j2') }}"
  when: (vol_pool.name not in poollist.list_pools)

- name: Starts os-volumes pool
  virt_pool:
    command: create
    name: "{{ vol_pool.name }}"
    autostart: 'yes'
  when: (vol_pool.name not in poollist.list_pools)
