---
############################################################
#  tasks file for destroying virtual storages
############################################################
- name: List virtual storage pools
  virt_pool:
    command: list_pools
  register: poollist

- name: Refresh storage pool list
  command: virsh pool-refresh "{{ vol_pool.name }}"
  when: vol_pool.name in poollist.list_pools
  ignore_errors: 'yes'

- name: Stop os-volumes pool
  virt_pool:
    command: destroy
    name: "{{ vol_pool.name }}"
  when: vol_pool.name in poollist.list_pools
  ignore_errors: 'yes'

- name: Remove os-volumes pool
  virt_pool:
    command: undefine
    name: "{{ vol_pool.name }}"
  when: vol_pool.name in poollist.list_pools
  ignore_errors: 'yes'

- name: Check if folder already exists
  stat:
    path: "{{ vol_pool.path }}"
  register: folderonplace

- name: Remove os-volumes folder
  file:
    path: "{{ vol_pool.path }}"
    state: absent
  when: folderonplace.stat.exists
  ignore_errors: 'yes'
