---
- name: Converge
  hosts: all
  gather_facts: 'no'

  collections:
    - kemopq.virtual_resources

  tasks:
    - name: "Include virtual_resources role"
      include_role:
        name: "virtual_resources"
